disabled_rules:
  - line_length
  - function_body_length

  - nesting
  - cyclomatic_complexity

  - force_try
  - force_cast
  - void_return
  - trailing_comma

  - weak_delegate
  - vertical_whitespace
  - identifier_name

  - inclusive_language

included:
  - Presentation
  - PresentationTests

excluded:
  - Examples

identifier_name:
  excluded: [vc, nc, i]
  severity: warning
